### ISSUE TITLE
[Question] Is really required MySQL database?

### ISSUE THREAD

**Issue by juaningan** [op5/merlin#1]
Hi, I'm evaluating Merlin for integrate in a Naemon + Mod-gearman distributed architecture where Naemon Core doesn't have redundacy because of stateful data (comments, acks...).

I guess that I can define my 2 Naemon Core as peers in Merlin to sync stateful data. But, my question is. Why I need MySQL DB? Can I not to sync directly daemon to daemon?

Thanks.

**Comment by mattiasr** [comment]
It's late now so not 100 sure, but if i recall correctly the db is only for report support.

You can set some setting merlin.conf to not log to database.

/Mattias

**Comment by juaningan** [comment]
OK. I've tested without database and it works. Thanks.
