### ISSUE TITLE
Steps to install Merlin

### ISSUE THREAD

**Issue by coolvixs** [op5/merlin#16]
Hi All,

does anyone has the steps especially what changes need to be done to configs in order to install merlin with naemon on centos 7.

especially if the ./autogen.sh can do the necessary checks.

I know am asking for alot, but would appreciate.

Thanks,

**Comment by tvestelind** [comment]
Maybe this Dockerfile could help a bit? 

https://github.com/tvestelind/merlin/blob/feature/parallel-tests/docker/centos6/Dockerfile

**Comment by coolvixs** [comment]
Thanks that was very help. using the docker file as instructions i was able to install merlin.

appreciate your help.
