### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by LikoV2** [op5/merlin#19]
Hi,

I'm on CentOS 7. Here is the installation process:

git clone https://github.com/op5/merlin.git
cd merlin
./autogen.sh -> No errors
make 

make[1]: Entering directory `/usr/local/merlin/merlin'
  CC       shared/merlin_la-shared.lo
In file included from shared/shared.c:8:0:
shared/node.h:245:2: error: unknown type name 'nm_bufferqueue'
  nm_bufferqueue *bq;     /* I/O cache for bulk reads */
  ^
make[1]: *** [shared/merlin_la-shared.lo] Error 1

First time I encounter this error, unfortunately I don't have the knowledge to solve it by myself.

Thanks.

**Comment by tvestelind** [comment]
Hi,

I `nm_bufferqueue` is declared in naemon's headers. Although autoconf looks whether naemon is installed on your system, I'm not sure that it checks whether the headers are installed. Are the naemon headers files installed?

Best Regards,
Tomas

**Comment by LikoV2** [comment]
Hi Tomas,

Thanks for your response. I installed naemon like this:

wget -A rpm -mpEkKnp -nd https://labs.consol.de/naemon/release/v1.0.3/rhel7/x86_64/
yum install *.rpm

All went smooth, but I don't see a .rpm with naemon headers.

**Comment by tvestelind** [comment]
Is `naemon-devel` installed? If so then I think it should install headers somewhere like `/usr/include/naemon` (you can check using `rpm -ql naemon-devel`

**Comment by LikoV2** [comment]
I ran "rpm -ql naemon-devel". A list appeared with around 30 .h in /usr/include/naemon.

So yes, I think it's installed.

**Comment by tvestelind** [comment]
You're actually using quite an old version of naemon which doesn't have that type declared.

```
commit 94e4182e5dd8ef9a9f03262daf9e408c6f7bb0b4 (HEAD, tag: v1.0.3)
Author: Sven Nierlein <Sven.Nierlein@consol.de>
Date:   Sun Mar 29 23:42:39 2015 +0200

    released 1.0.3
    
    Signed-off-by: Sven Nierlein <Sven.Nierlein@consol.de>
```

I'm not sure if there are newer version available as RPM-packages or if you could build the naemon stuff yourself.
An alternative could be to use an older version of merlin, but I wouldn't recommend it.

**Comment by LikoV2** [comment]
Oh, I see, sorry about that.

I will try to install naemon via git, thanks for your help !

**Comment by tvestelind** [comment]
No problem. Let me know if you need more help.

**Comment by LikoV2** [comment]
Sorry to bother you again, but I have an issue with headers again. I'm working on a clean server.

I installed naemon via git, it went smooth. I installed merlin, too, but during ./autogen.sh, I have this error:

checking for naemon... no
configure: error: Package requirements (naemon >= 0.8) were not met:

No package 'naemon' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

I checked in /usr/lib64/pkgconfig/ there is no naemon.pc. Do I have to create it manually ? The installer talks about naemon_CFLAGS and naemon_LIBS, but there is no documentation on it anywhere.

**Comment by tvestelind** [comment]
I've made a docker container in a private branch. Maybe you could get some inspiration from that one:

https://raw.githubusercontent.com/tvestelind/merlin/feature/parallel-tests/docker/centos6/Dockerfile

**Comment by LikoV2** [comment]
Thanks, now I see. I re-installed nagios core, and I specified --prefix and --libdir. That did the trick.

**Comment by jacobbaungard** [comment]
Hi,

@LikoV2 can this issue be closed?

If you do not specify an install prefix when installing Naemon from source, then naemon.pc will be installed at: /usr/local/lib/pkgconfig/ . In order to allow the Merlin configure script to find Naemon correctly you can add the following environment variable:

`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/`

**Comment by LikoV2** [comment]
Hi,

Yes it can be closed, thanks for the help.
