### ISSUE TITLE
./configure not found

### ISSUE THREAD

**Issue by misterpremium** [op5/merlin#26]
Hi

When i download he .tar and uncompress it, i cant find the configure file. I cant execute ./autogen.sh

#./autogen.sh 
Can't exec "aclocal": No existe el fichero o el directorio at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No existe el fichero o el directorio
./autogen.sh: línea 4: ./configure: No existe el fichero o el directorio

Thanks

Regards

**Comment by jacobbaungard** [comment]
Have you installed automake?

**Comment by misterpremium** [comment]
Ok I install git and automake but its throw me other erro 

#./autogen.sh 
configure.ac:14: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."


#ls -ltr
total 496
drwxr-xr-x 2 1000 1000     47 jul 19 11:51 xdoc
drwxr-xr-x 2 1000 1000    252 jul 19 11:51 tools
drwxr-xr-x 5 1000 1000   4096 jul 19 11:51 tests
drwxr-xr-x 2 1000 1000     63 jul 19 11:51 test_protocol
-rw-r--r-- 1 1000 1000   5303 jul 19 11:51 TECHNICAL
drwxr-xr-x 2 1000 1000     23 jul 19 11:51 sudo
drwxr-xr-x 3 1000 1000     71 jul 19 11:51 sql
-rw-r--r-- 1 1000 1000   4382 jul 19 11:51 SPECS
-rwxr-xr-x 1 1000 1000    920 jul 19 11:51 sort-merge_logs.sh
drwxr-xr-x 2 1000 1000   4096 jul 19 11:51 shared
-rw-r--r-- 1 1000 1000   9760 jul 19 11:51 README.md
lrwxrwxrwx 1 1000 1000      9 jul 19 11:51 README -> README.md
drwxr-xr-x 2 1000 1000     49 jul 19 11:51 op5build
-rw-r--r-- 1 1000 1000   1777 jul 19 11:51 nrpe-merlin.cfg
-rw-r--r-- 1 1000 1000    115 jul 19 11:51 NEWS
drwxr-xr-x 2 1000 1000    310 jul 19 11:51 module
-rw-r--r-- 1 1000 1000   9849 jul 19 11:51 merlin.spec
-rw-r--r-- 1 1000 1000  43131 jul 19 11:51 merlin_logo.svg
-rw-r--r-- 1 1000 1000    349 jul 19 11:51 merlind.service
-rw-r--r-- 1 1000 1000  13732 jul 19 11:51 Makefile.am
drwxr-xr-x 2 1000 1000     26 jul 19 11:51 m4
drwxr-xr-x 2 1000 1000     89 jul 19 11:51 logs
-rwxr-xr-x 1 1000 1000   2616 jul 19 11:51 install-merlin.sh.in
-rw-r--r-- 1 1000 1000  31696 jul 19 11:51 HOWTO
-rwxr-xr-x 1 1000 1000    140 jul 19 11:51 generate_version_number.sh
drwxr-xr-x 4 1000 1000   4096 jul 19 11:51 features
-rw-r--r-- 1 1000 1000    825 jul 19 11:51 doxy.conf
drwxr-xr-x 2 1000 1000    121 jul 19 11:51 data
drwxr-xr-x 2 1000 1000    293 jul 19 11:51 daemon
-rw-r--r-- 1 1000 1000  18886 jul 19 11:51 COPYING
-rw-r--r-- 1 1000 1000   6292 jul 19 11:51 configure.ac
drwxr-xr-x 2 1000 1000     41 jul 19 11:51 compat
-rw-r--r-- 1 1000 1000     51 jul 19 11:51 ChangeLog
-rwxr-xr-x 1 1000 1000     67 jul 19 11:51 autogen.sh
-rw-r--r-- 1 1000 1000    116 jul 19 11:51 AUTHORS
drwxr-xr-x 4 1000 1000    127 jul 19 11:51 apps
-rw-r--r-- 1 root root  55255 jul 20 09:21 aclocal.m4
drwxr-xr-x 2 root root     86 jul 20 09:21 autom4te.cache
-rwxr-xr-x 1 root root 223753 jul 20 09:21 configure
-rw-r--r-- 1 root root   4932 jul 20 09:21 config.log


Thanks and regards
