### ISSUE TITLE
pkg-config issue on CentOS 7

### ISSUE THREAD

**Issue by SeLLeRoNe** [op5/merlin#6]
Hi, i'm trying to build merlin from git repository, on the autogen.sh execution (well, actually on the ./configure) , i've got this error:

./configure: line 12732: syntax error near unexpected token `naemon,'
./configure: line 12732: `PKG_CHECK_MODULES(naemon, naemon >= 0.8)'

Googling a bit i've found out that this happen when pkg-config is not installed, but actually it is:
pkg-config --version
0.27.1

Also naemon-devel package is installed (with the dependency libnaemon) installed using this repo:
https://labs.consol.de/repo/stable/rhel7/i386/labs-consol-stable.rhel7.noarch.rpm

Does anyone have any suggestion to help me fix this strange issue?

Thanks
Best regards
Andrea

**Comment by tvestelind** [comment]
Hi,

I tried to reproduce this in a VM. This is what I used:
- merlin, commit 9b0e044eb25a198a3210bbe1dfcb4f3e9198a13c
- CentOS7:
```
$ hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 7d0066715f9941df9f68b91fe8b80dc0
           Boot ID: 533b0614610a4fccaa346160ad8e7fc2
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.el7.x86_64
      Architecture: x86-64
$ rpm --query centos-release
centos-release-7-2.1511.el7.centos.2.10.x86_64
```

and it works. 

Could you try running `autoreconf -si` again before running `autogen.sh`?

Best Regards,
Tomas

**Comment by SeLLeRoNe** [comment]
If i manually run autoreconf -si it return:
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.

Thanks

**Comment by tvestelind** [comment]
Hi again Andrea,

Thank you for the information. Could I just ask for some more info? More specifically the output from:
- hostnamectl
- rpm --query centos-release
- git log -1 --pretty=format:"%H"

Thanks

**Comment by SeLLeRoNe** [comment]
Sure thing!
>hostnamectl
   Static hostname: Home.Test-Server.it
         Icon name: computer-vm
           Chassis: vm
        Machine ID: cd7db6f98a104a36a97c98f69b1fafcd
           Boot ID: e600786f48404652863a9ec4d9939325
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.36.3.el7.x86_64
      Architecture: x86-64

>rpm --query centos-release
centos-release-7-2.1511.el7.centos.2.10.x86_64


>git log -1 --pretty=format:"%H"
9b0e044eb25a198a3210bbe1dfcb4f3e9198a13c


Thanks for your help

**Comment by SeLLeRoNe** [comment]
Also, just in case, this is a test VM where i test scripts, so, if you want i have no problem to share the access to it if you wanna debug it a bit.

Thanks

**Comment by tvestelind** [comment]
Hi again,

Sure, if you could get me SSH access that would be great :)

BR,
Tomas

**Comment by SeLLeRoNe** [comment]
Hi Tomas,

here it is:

Host: home.test-server.it

Port: 2288

User: tomas

Pass: 6z2iEnui0O

SU pass: password123

Merlin repository is cloned in /usr/local/crazynetwork/monitor/merlin

Naemon is installd from source and it is in: /usr/local/naemon


Feel free to mess around, i hope you'll find the cause of the issue :)


Thanks for your time

Andrea

**Comment by tvestelind** [comment]
Hi Andrea,

I doesn't work for me but we can take it in private messages so that not everyone can access your private server ;)

**Comment by SeLLeRoNe** [comment]
Oh i tought it was a private email the one i'd replied to :)

It is a home server, so was off during the night, now it is on again but i've changed the password for your account, i'm gonna pm you the new one

**Comment by tvestelind** [comment]
After a bit of troubleshooting it seems like you have an older version of autoconf and a newer version of automake in /usr/local/bin. It might have been this combination that generated an invalid 'configure'.

I think you might need to clean up your system a bit, did you build and install autoconf/automake yourself maybe? Anyway, try this `export PATH=/usr/sbin:/usr/bin:/root/bin` and you should be able to run `./autogen.sh`, `make` and `make install`.

Best Regards,
Tomas

**Comment by SeLLeRoNe** [comment]
Hi Tomas,

Thanks a lot for your time and for the solution.

Yes, actually both automake and autoconf has been installed by source (and yes probably also by yum)
The version installed by source should be:
automake 1.15
autoconf 2.68

Those should be the latest versions actually, and the system should be using them:
>which autoconf
/usr/local/bin/autoconf
>/usr/local/bin/autoconf --version
autoconf (GNU Autoconf) 2.68

>which automake
/usr/local/bin/automake
>/usr/local/bin/automake --version
automake (GNU automake) 1.15

So, here is clear that the system should us "as default" the latest versions, sayd that, if i manually run the one in /usr/bin they are:
>/usr/bin/autoconf --version
autoconf (GNU Autoconf) 2.69
>/usr/bin/automake --version
automake (GNU automake) 1.13.4

So, system level, autoconf is actually newer while automake is older:
>rpm -q automake
automake-1.13.4-3.el7.noarch
[01:53:59] root@Home.Test-Server.it [/usr/local/crazynetwork/monitor/merlin]
>rpm -q autoconf
autoconf-2.69-11.el7.noarch

And no i'm a bit confused..

In /usr/bin i have version installed by YUM, in /usr/local/bin i've version manually installed (autoconf is not exactly latest, but 1 version behind, while automake is way newer, still, "which" command say /usr/local/bin so shoudln't the "autogen.sh" and  "configure" use the one from "which" output?

Thanks for clarification.

Best regards
Andrea

**Comment by SeLLeRoNe** [comment]
I've compiled autoconf 2.69 from souce, so now in /usr/bin and /usr/local/bin there is the same autoconf version.

**Comment by tvestelind** [comment]
Yes, I think you are right and I think it's reasonable to assume that we should be able to build with the latest of both autoconf and automake.

If I have time I can try to investigate this a bit more, either to find what I need to change or to just put limits on the versions of autoconf and automake that are supported. 
If you have time to look for a solution, please do, it will be greatly appreciated! :smile: 

Thanks for your time!

Best Regards,
Tomas

**Comment by SeLLeRoNe** [comment]
I may have found the issue.

pkg-config itself, i'm using the OS one which is version 0.27.1
If i manually intall pkg-config 0.29 the result change:

checking whether C compiler accepts -Wno-error=unused-result... yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for naemon... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for GLIB... no
configure: error: Package requirements (glib-2.0) were not met:

No package 'glib-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB_CFLAGS
and GLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Apparently, with latest pkg-config i can pass that error, but than (and this sound obvrious) the manually installed pkg-config (simply configure make make install) doesn't find needed packages.

So, now i'm googling a bit for issue between pkg-config 0.27.1 and automake 1.15.

I hope this will bring us somewhere :)

Best regards

**Comment by SeLLeRoNe** [comment]
Ok, just exporting the PKG_CONFIG_PATH variable did the trick: export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib64/pkgconfig

**Comment by tvestelind** [comment]
Hi again,

Thank you for your great detective work! :smile: 

I'm using the following:
```
[root@localhost ~]# pkg-config --version
0.27.1
[root@localhost ~]# autoconf --version
autoconf (GNU Autoconf) 2.69
[root@localhost ~]# automake --version
automake (GNU automake) 1.13.4
```
which is what's in the CentOS7 repos and this works.

If someone builds and installs version 1.15 of automake but doesn't do the same with version 0.29 of pkg-config then it will not work apparently. 

The question is if we need to keep track of dependency somehow, and if so, how can we do that?

**Comment by SeLLeRoNe** [comment]
Well, my suggestion would be a check somehow like (i use bash, no idea on other codes)

```
AUTOMAKE=`which automake`
AUTOMAKE_VER=`$AUTOMAKE --version | head -1 | cut -d\  -f4`
echo "automake version: $AUTOMAKE_VER"
AUTOMAKE_VER=`echo $AUTOMAKE_VER'>='1.15 | bc -l`
PKGCONFIG=`which pkg-config`
PKGCONFIG_VER=`$PKGCONFIG --version`
echo "pkgconfig version: $PKGCONFIG_VER"
PKGCONFIG_VER=`echo $PKGCONFIG_VER'<'0.29 | bc -l`

if [ "$AUTOMAKE_VER" -eq 1 -a "$PKGCONFIG_VER" -eq 1 ]; then
echo "ERROR"
else
echo "OK"
fi
```

In this case, it save the value of the version and compare tham with the "wrong combination", so if the if is success, it mean that you have automake at least at version 1.15 and phpconfig lower than version 0.29.

It also show the output of the two versions.

Hope this help :)
Best regards

**Comment by tvestelind** [comment]
Hi again,

I think it will be too much to keep track of which combinations of autoconf, automake and pkgconfig that works. The easiest is probably to go with what's in the repos in the CentOS versions so I will not go further with this at the moment.

Thanks for all your effort and the information in this issue will hopefully help other people running into these kind of problems :)

Best Regards,
Tomas

**Comment by SeLLeRoNe** [comment]
Thank to you for your time :)

Best regards
Andrea
